version: '3'
services:
  api_server:
    image: node:latest
    working_dir: /api
    ports:
      - "3000:3000"
    volumes:
      - .:/api
    command: >
      sh -c "npm install && npm run build-tsc && node ./.dist/src/server.js"
